plugins {
 id 'java-library'
 id 'net.neoforged.gradle.userdev' version '7.1.38'
}
version='2.3.1'
group='jp.chatgpt'
base { archivesName='fantasy_armor_iss' }
java.toolchain.languageVersion=JavaLanguageVersion.of(21)
repositories { mavenCentral() }
dependencies { implementation 'net.neoforged:neoforge:21.1.219' }
runs { client { client() } }
